import Image from 'next/image';import Link from 'next/link';import {ArrowRight,Gift,Leaf,PackageCheck,Truck} from 'lucide-react';import HomeProducts from '@/components/HomeProducts';
const cats=[['Qulupnay boxlar','/products/strawberry-box.jpg'],['Shokoladli mahsulotlar','/products/american-chocolate.jpg'],['Kruassanlar','/products/croissant-mix.jpg'],['Mevali boxlar','/products/assorti-mix-80.jpg'],['Qulupnay & banan','/products/strawberry-banana.jpg'],['Sovg‘a boxlar','/products/assorti-mix-85.jpg']];
export default function Home(){return <>
<section className="hero"><div className="hero-copy"><div className="eyebrow">TOSHKENTDA MEHR BILAN TAYYORLANGAN</div><h1>Shirin lahzalarni<br/><em>Lookberry</em> bilan yarating <span>♥</span></h1><p>Yangi mevalar, shokolad va kruassanlardan tayyorlangan maxsus boxlar.</p><div className="hero-buttons"><Link className="primary" href="/products">Mahsulotlarni ko‘rish <ArrowRight/></Link><Link className="secondary" href="/checkout">Buyurtma berish</Link></div><div className="hero-notes"><span><b>10+</b> maxsus box</span><span><b>100%</b> yangi mahsulot</span></div></div><div className="hero-visual"><div className="berry berry-one">♥</div><Image src="/products/assorti-mix-85.jpg" alt="Lookberry assorti mix premium sovg‘a boxi" fill priority sizes="(max-width:800px) 100vw, 52vw"/><div className="hero-tag"><small>Bugungi tanlov</small><b>Assorti Mix</b><span>85 000 so‘m</span></div></div></section>
<section className="marquee"><span>YANGI QULUPNAY</span>✦<span>PREMIUM SHOKOLAD</span>✦<span>MEHR BILAN QADOQLANGAN</span>✦<span>TEZKOR YETKAZIB BERISH</span></section>
<section className="section" id="categories"><div className="section-head"><div><span className="kicker">DIDINGIZGA MOS</span><h2>Kategoriyalar</h2></div><p>Har bir lahza uchun alohida,<br/>o‘zgacha ta’m.</p></div><div className="category-grid">{cats.map(([name,img],i)=><Link href={`/products?category=${encodeURIComponent(name)}`} className={`category c${i}`} key={name}><Image src={img} alt={name} fill sizes="(max-width:600px) 50vw, 33vw"/><div><span>0{i+1}</span><h3>{name}</h3><b>Ko‘rish →</b></div></Link>)}</div></section>
<section className="section products-section"><div className="section-head"><div><span className="kicker">ENG SEVIMLILAR</span><h2>Shirin tanlovlar</h2></div><Link href="/products">Barchasini ko‘rish <ArrowRight size={18}/></Link></div><HomeProducts/></section>
<section className="story" id="about"><div className="story-image"><Image src="/products/strawberry-box.jpg" alt="Lookberry shokoladli qulupnay box" fill sizes="50vw"/></div><div className="story-copy"><span className="kicker">BIZNING HIKOYA</span><h2>Har bir box —<br/><em>mehr izhori</em></h2><p>Lookberry’da har bir meva ehtiyotkorlik bilan tanlanadi, har bir detal esa mehr bilan bezatiladi. Chunki sovg‘a — bu shunchaki mahsulot emas, bu sizning hislaringiz.</p><div className="signature">LOOKBERRY <span>♥</span></div><Link className="text-link" href="/products">O‘zingizga mos boxni tanlang <ArrowRight/></Link></div></section>
<section className="delivery section" id="delivery"><div className="center"><span className="kicker">SIZ UCHUN QULAYLIK</span><h2>Lookberry sizga yetib boradi <span>♥</span></h2></div><div className="benefits"><div><Truck/><h3>Yetkazib berish</h3><p>Buyurtmangizni belgilangan vaqtda ehtiyotkorlik bilan yetkazamiz.</p></div><div><Gift/><h3>Chiroyli qadoqlash</h3><p>Har bir box sovg‘a qilishga tayyor premium qadoqda.</p></div><div><Leaf/><h3>Yangi mahsulot</h3><p>Faqat saralangan yangi meva va sifatli shokolad.</p></div><div><PackageCheck/><h3>Tezkor xizmat</h3><p>Oddiy buyurtma jarayoni va tezkor tasdiqlash.</p></div></div></section>
<section className="instagram section"><div className="insta-copy"><span className="kicker">BIZNI KUZATING</span><h2>Lookberry bilan<br/>yanada yaqinroq bo‘ling</h2><p>@lookberry_uz</p><a className="primary" target="_blank" href="https://www.instagram.com/lookberry_uz">Instagram’ga o‘tish <ArrowRight/></a></div><div className="insta-grid">{['croissant-oreo.jpg','strawberry-standard.jpg','strawberry-banana.jpg','croissant-mix.jpg'].map((x,i)=><a href="https://www.instagram.com/lookberry_uz" target="_blank" key={x}><Image src={`/products/${x}`} alt={`Lookberry Instagram mahsuloti ${i+1}`} fill sizes="25vw"/></a>)}</div></section>
</>}
